export * from './CursoHeader'
export * from './CursoDetalleSkeleton'
export * from './CursoTabs'
export * from './PestanaEstudiantes'
export * from './PestanaCargaAcademica'
export * from './EstudiantesMatriculadosTable'
export * from './EstudianteMatriculadoFila'
export * from './EstudiantesCursoEmptyState'
